<?php

namespace AkademiaBundle\Repository;

/**
 * TemporadaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use Doctrine\DBAL\DBALException;
class TemporadaRepository extends \Doctrine\ORM\EntityRepository
{



	public function getTemporadaActiva(){

        try {
				$query = "	SELECT temp.id temporadaId
							FROM ACADEMIA.temporada temp WHERE estado = 1;";

			    $stmt = $this->getEntityManager()->getConnection()->prepare($query);
			    $stmt->execute();
			    $temporadaActiva = $stmt->fetchAll();
           		return $temporadaActiva;

        }catch (DBALException $e) {
          $message = $e->getCode();
        }

        return $message;
	}

	public function getTemporadasHabilitadas(){

        try {
				$query = "	SELECT temp.id temporadaId, cic.descripcion ciclo, temp.anio anio
							FROM ACADEMIA.temporada temp
							INNER JOIN ACADEMIA.ciclo cic ON cic.id = temp.ciclo_id
							WHERE
							GETDATE() BETWEEN apertura AND fecha_subsanacion";

			    $stmt = $this->getEntityManager()->getConnection()->prepare($query);
			    $stmt->execute();
			    $temporadas = $stmt->fetchAll();
           		return $temporadas;

        }catch (DBALException $e) {
          $message = $e->getCode();
        }

        return $message;
	}

	public function updateTemporada($editarAnio,$editarCiclo,$editarApertura,$editarPreInscripcion,$editarInicioClases,$editarCierreClases,$editarFechaSubsanacion,$idTemporada){

            try {
					$query = "	UPDATE ACADEMIA.temporada SET
								anio = $editarAnio,
								ciclo_id = $editarCiclo ,
								apertura = '$editarApertura' ,
								pre_inscripciones='$editarPreInscripcion',  
								inicio_clases='$editarInicioClases',
								cierre_clases='$editarCierreClases',
								fecha_subsanacion='$editarFechaSubsanacion' WHERE id = $idTemporada";
				    $stmt = $this->getEntityManager()->getConnection()->prepare($query);
				    $stmt->execute();

               		$message = 2;

            }catch (DBALException $e) {
              $message = $e->getCode();
            }

            return $message;
	}

	public function getTemporadas(){

		$query = "	SELECT	temp.id,
							temp.anio,
							cic.descripcion ciclo,
							temp.ciclo_id cicloId,
							CONVERT(varchar,temp.apertura,105) apertura,
							CONVERT(varchar,temp.pre_inscripciones,105) pre_inscripciones,
							CONVERT(varchar,temp.inicio_clases,105) inicio_clases,
							CONVERT(varchar,temp.cierre_clases,105) cierre_clases,
							CONVERT(varchar,temp.fecha_subsanacion,105) subsanacion,
							CONVERT( VARCHAR,DATEDIFF(month,temp.apertura,temp.cierre_clases) )+' meses' duracion,
							temp.estado
					FROM ACADEMIA.temporada temp
					INNER JOIN ACADEMIA.ciclo cic ON cic.id = temp.ciclo_id ORDER BY temp.id DESC";
	    
	    $stmt = $this->getEntityManager()->getConnection()->prepare($query);
	    $stmt->execute();
	    $temporadas = $stmt->fetchAll();
	    
	    return $temporadas;
	}

	public function getCantidadMesesTemporadaEnCurso($idTemporada){

		$query = "	SELECT	
					MONTH(temp.inicio_clases) mes_inicio_temporada,
					MONTH(temp.cierre_clases) mes_fin_temporada 
					FROM ACADEMIA.temporada temp
					INNER JOIN ACADEMIA.ciclo cic ON cic.id = temp.ciclo_id
					WHERE temp.id = $idTemporada; ";
	    
	    $stmt = $this->getEntityManager()->getConnection()->prepare($query);
	    $stmt->execute();
	    $mesesTemporada = $stmt->fetchAll();
	    
	    return $mesesTemporada;
	}
}
