
#akademia_exportExcelPrueba:
#  path: /exporExcelPrueba
#  defaults: { _controller: AkademiaBundle:ExportacionData:exportPrueba }


##PAGINA principal

akademia_paginaPreHorarios:
    path: /pre-horarios/{estado}
    defaults: { _controller: AkademiaBundle:Default:paginaPreHorarios}

akademia_paginaPreInscripcion:
    path: /pre-inscripcion
    defaults: { _controller: AkademiaBundle:Default:indexPreInscripcion}

##END

## LOGIN - INICIO DE SESSION
akademia_login:
    path:    /login
    defaults: {_controller: AkademiaBundle:Login:login}

akademia_login_check:
    path:    /login_check

akademia_logout:
    path:    /logout

##END

entradas_list:
    path: /pruebas/entradas
    defaults: { _controller: AppBundle:Pruebas:entradas}

akademia_contador:
    path:     /contador
    defaults: { _controller: AkademiaBundle:Default:contador }
    
akademia_panel:
    path:     /panel
    defaults: { _controller: AkademiaBundle:Default:panel}
    methods:  [GET,POST]

akademia_getPost:
    path:     /ajax/post/get
    defaults: { _controller: AkademiaBundle:Default:post}
    methods:  [GET,POST]


## PRE INSCRIPCION

akademia_homepage:
    path:     /
    defaults: { _controller: AkademiaBundle:Preinscripcion:index }
    methods:  [GET,POST]

akademia_registrar:
    path:     /ajax/registrar
    defaults: { _controller: AkademiaBundle:Preinscripcion:registrar }
    methods:  [GET,POST]

akademia_registroFinal:
    path:     /registrofinal/{estado}
    defaults: { _controller: AkademiaBundle:Preinscripcion:registroFinal }
    methods:  [GET,POST]

akademia_generarPdfInscripcion:
    path:     /ajax/pdf/inscripcion/{id}
    defaults: { _controller: AkademiaBundle:Preinscripcion:generarPdfInscripcion}
    methods:  [GET,POST]

akademia_generarPdfDeclaracionJurada:
    path:     /ajax/pdf/declaracion-jurada/{id}
    defaults: { _controller: AkademiaBundle:Preinscripcion:generarPdfDeclaracionJurada}
    methods:  [GET,POST]

akademia_sendemail:
    path:     /ajax/sendemail
    defaults: { _controller: AkademiaBundle:Preinscripcion:sendemail}
    methods:  [GET,POST]

akademia_sendemailapoderado:
    path:     /ajax/sendemailapoderado
    defaults: { _controller: AkademiaBundle:Preinscripcion:sendemailapoderado}
    methods:  [GET,POST]

## END 

akademia_prueba:
    path:     /prueba
    defaults: { _controller: AkademiaBundle:Default:prueba}
    methods:  [GET,POST]

akademia_sendemailusuario:
    path:     /ajax/sendemailusuario
    defaults: { _controller: AkademiaBundle:Default:sendemailusuario}
    methods:  [GET,POST]

akademia_consulta:
    path:     /consulta
    defaults: { _controller: AkademiaBundle:Default:consulta}
    methods:  [GET,POST]


akademia_mostrarcomplejos:
    path:    /ajax/mostrarcomplejos
    defaults: {_controller: AkademiaBundle:Default:mostrarcomplejos}
    methods: [GET,POST]

akademia_inscritos:
    path:    /inscritos
    defaults: {_controller: AkademiaBundle:Default:inscritos}
    methods: [GET,POST]
  
## MOD HORARIOS
akademia_mostrarHorarioIndividual:
   path:    /ajax/mostrarHorarioIndividual
   defaults: {_controller: AkademiaBundle:Horario:mostrarHorarioIndividual}
   methods: [GET,POST]

akademia_crearHorario:
   path:    /ajax/crearHorario
   defaults: {_controller: AkademiaBundle:Horario:crearHorario}
   methods: [GET,POST]

akademia_actualizarHorario:
   path:    /ajax/actualizarHorario
   defaults: {_controller: AkademiaBundle:Horario:actualizarHorario}
   methods: [GET,POST]

akademia_ocultarHorario:
   path:    /ajax/ocultarHorario
   defaults: {_controller: AkademiaBundle:Horario:ocultarHorario}
   methods: [GET,POST]

akademia_horarios:
    path:    /horarios
    defaults: {_controller: AkademiaBundle:Horario:horarios}
    methods: [GET,POST]

##END

## MOD DISCIPLINAS
akademia_crearDisciplina:
   path:    /ajax/crearDisciplina
   defaults: {_controller: AkademiaBundle:Disciplina:crearDisciplina}
   methods: [GET,POST]

akademia_eliminarDisciplina:
    path:     /ajax/eliminarDisciplina
    defaults: { _controller: AkademiaBundle:Disciplina:eliminarDisciplina}  
    methods:  [GET,POST]
##END

## VALIDAR FICHA
akademia_cambiarestado:
    path:   /ajax/cambiarestado
    defaults: {_controller: AkademiaBundle:Ficha:cambiarestado}
    methods: [GET, POST]

akademia_mostrarficha:
    path:     /ajax/mostrarficha
    defaults: { _controller: AkademiaBundle:Ficha:mostrarficha }
    methods:  [GET,POST]

akademia_configuracion:
    path:     /ajax/configuracion
    defaults: { _controller: AkademiaBundle:Default:configuracion}
    methods:  [GET,POST]

akademia_login:
    path:    /login
    defaults: {_controller: AkademiaBundle:Default:login}

## END 

## MOD CONFIGURACION
akademia_configuracion:
    path:     /ajax/configuracion
    defaults: { _controller: AkademiaBundle:Configuracion:configuracion}
    methods:  [GET,POST]

##END 

## MOD BENEFICIARIOS Y TALENTOS

akademia_estadoBeneficiario:
    path:     /estadoBeneficiario
    defaults: { _controller: AkademiaBundle:Beneficiario:estadoBeneficiario}
    methods:  [GET,POST]

akademia_beneficiarios:
    path:    /beneficiarios/{idHorario}
    defaults: {_controller: AkademiaBundle:Beneficiario:beneficiarios}
    methods: [GET,POST]

akademia_cantInscritos:
    path:    /ajax/cantInscritos
    defaults: {_controller: AkademiaBundle:Beneficiario:cantInscritos}
    methods: [GET,POST]


akademia_evaluados:
    path:     /ajax/evaluados
    defaults: { _controller: AkademiaBundle:Talentos:evaluados}
    methods:  [GET,POST]

akademia_talentos:
    path:     /ajax/talentos/{idParticipante}
    defaults: { _controller: AkademiaBundle:Talentos:talentos}
    methods:  [GET,POST]

akademia_guardarTalento:
    path:     /ajax/guardarTalento
    defaults: { _controller: AkademiaBundle:Talentos:guardarTalento}
    methods:  [GET,POST]

akademia_mostrarControlesInd:
    path:     /ajax/mostrarControlesInd
    defaults: { _controller: AkademiaBundle:Talentos:mostrarControlesInd}
    methods:  [GET,POST]

akademia_mostrarControlesInd:
    path:     /ajax/mostrarControlesInd
    defaults: { _controller: AkademiaBundle:Talentos:mostrarControlesInd}
    methods:  [GET,POST]

akademia_nuevoControl:
    path:     /ajax/control
    defaults: { _controller: AkademiaBundle:Talentos:nuevoControl}  
    methods:  [GET,POST]

akademia_actualizarIndicador:
    path:     /ajax/actualizarControl
    defaults: { _controller: AkademiaBundle:Talentos:actualizarControl}
    methods:  [GET,POST]

akademia_mostrarTalentos:
    path:     /ajax/mostrarTalentos
    defaults: { _controller: AkademiaBundle:Talentos:mostrarTalentos}
    methods:  [GET,POST]

akademia_mostrarDetalleTalento:
    path:     /ajax/detalle/{idParticipante}
    defaults: { _controller: AkademiaBundle:Talentos:mostrarDetalleTalento}
    methods:  [GET,POST]

akademia_nuevoTalento:
    path:     /ajax/nuevoTalento
    defaults: { _controller: AkademiaBundle:Talentos:nuevoTalento}  
    methods:  [GET,POST]

##END 

akademia_visibilidadApp:
    path:     /ajax/visibilidadApp
    defaults: { _controller: AkademiaBundle:Talentos:visibilidadApp}  
    methods:  [GET,POST]


##INCIO EXPORTAR DATA ##
akademia_export:
   path:    /export
   defaults: {_controller: AkademiaBundle:ExportacionData:export}
   methods: [GET,POST]

akademia_exportCantidadPreInscritos:
   path:    /exportCantidadPreInscritos
   defaults: {_controller: AkademiaBundle:ExportacionData:exportCantidadPreInscritos}
   methods: [GET,POST]

akademia_exportCantidadInscritos:
   path:    /exportCantidadInscritos
   defaults: {_controller: AkademiaBundle:ExportacionData:exportCantidadInscritos}
   methods: [GET,POST]

akademia_exportCantidadHorariosCreadosRegion:
   path:    /exportCantidadHorariosCreadosRegion
   defaults: {_controller: AkademiaBundle:ExportacionData:exportCantidadHorariosCreadosRegion}
   methods: [GET,POST]

akademia_exportData:
   path:    /exportData
   defaults: {_controller: AkademiaBundle:ExportacionData:exportData}
   methods: [GET,POST]
#FIN 

#### INICIO API REST 


